#KitPvP Version BUILD-19 | Author: zEnderX5_ , Rafael Auler
#Author Channel: https://www.youtube.com/channel/UCb1kjbiQj2B4KnRQpgeUwmQ
#Subscribe to help me to improve the plugin. Thanks =D
#PS: use /kp for view the plugin command list
#ALL MESSAGES SUPPORT COLORS! 
#View all colors here: http://minecraft.tools/en/color-code.php
#The plugin only works on 1.7 if you use BUILD-10 or lower
#BUILD-14 is for 1.8 or greater servers

#Prefix settings
Prefix: '&8[&cKitPvP&8] '

#No Permission Message 
#ALL PERMISSIONS IS LISTED HERE: https://pastebin.com/JuMPHpRD
Permission: '&cSorry, but you dont have the permission to use this.'

#Kill & Death settings
CustomKillAndDeathMessage: true

#Message settings
Message:
  Kit: '&aYou have chosen kit &8- &a%kit%!'
  KitUse: '&cYou have already taken a kit'
  Death: '&cYou are killed by &7%player%'
  Kill: '&cYou killed the player &7%player%'
  Clear: '&cYou reset your kit'
  KitPvpJoin-Message: '&eYou join in the kitpvp'
  KitPvpLeave-Message: '&eYou leave the kitpvp'
  BlockedCMD-OnKitPvP: '&eThis command cannot be perfomed on kitpvp!'
#Kit Menu item settings
JoinItem:
 
  Lore: '&7Right click to open the kit menu'
  Spawn: 'spawn %player%'
  OpenKitMenu: 'false'
  JoinSound: 'true'
   
  
#Spiderman settings
SidermanKit:
  Name: '&aWall Climber &7(Right click)'
  Lore: '&7(Right click) wall climber'
#Airman settings
AirmanKit:
  Name: '&aFly &7(Right click)'
  Lore: '&7(Right click) to fly'

#Title settings
#Only works on 1.8 or greater servers
Title:
  KitTitle: '&aYou have chosen the kit'
  KitSubTitle: '&aKit &8- &a%kit% !'
  DeathTitle: '&cYou are killed'
  DeathSubTitle: '&cby &7%player%'
  JoinTitle: '&eYou joined on the kitpvp'
  JoinSubTitle: '&eHave a great game!'
  LeaveTitle: '&cYou leave the kitpvp!'
  LeaveSubTitle: '&cTo join again use: /kitpvp join'
#Respawn settings
RespawnSound: true

#Sound list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
Sound:
  Kit: 'ITEM_PICKUP'
  ShopMenu: 'CHEST_OPEN'
  KitUse: 'ENDERDRAGON_HIT'
  Soup: 'EAT'
  Fisherman: 'ENDERMAN_TELEPORT'
  Spiderman: 'SLIME_WALK'
  Respawn: 'LEVEL_UP'
  Join: 'LEVEL_UP'
  KitMenu: 'DOOR_CLOSE'
  SpongeUse: 'ENDERMAN_TELEPORT'
  BowlDrop: 'ITEM_PICKUP'
  ErrorMessage: 'ARROW_HIT'
  SucefullMessage: 'ORB_PICKUP'
  NoPermissionMessage: 'WITHER_SHOOT'
  SwitcherShoot: 'ENDERMAN_TELEPORT'
  Timelord: 'WITHER_SPAWN'
  Stomper: 'FIREWORK_BLAST'
  NarutoAbility: 'BLAZE_DEATH'
  CommandsSounds: 'BURP'
  ShopMenu-Click: 'LEVEL_UP'
  Streak: 'LEVEL_UP'
  Airman-Fly: 'ENDERMAN_SCREAM'
  DoubleJump-Ability: 'FIREWORK_BLAST2'
  StomperDamage: 'ANVIL_LAND'
  1v1: 'CLICK'
  ClickTest: 'CLICK'

#If the option below is true all commands play a sound when a player execute them
#You can modify the sound in Sounds configuration
EnableSoundsToAllCommands: true

#If the option below is true the players cannot break or place blocks while in kitpvp
#Unless they have the permission kitpvp.build
#If the option is false everyone can build while in kitpvp unless you protect the zone with WorldGuard
#Defaults to true
BlockPlayersBuilding: true

#Enable or disable command block feature on kitpvp
#true means enabled / false means disabled
#Defaults to true
EnableCommandBlockingInKitPvP: true

#Enable or disable hunger on kitpvp
DisableHungerOnKitPvP: true

#Enable or disable droppig items while in kitpvp
#If this is true the player cannoy drop anhyting except bowls
#If this is false he can drop any item
#Recommended to leave this true
#Defaults to true
DisableDropsOnKitPvP: true

#Enable or disable pickup items on kitpvp
#If this is true the player can only pickup mushroom soups and bowls
#If this is false the player can pickup any items
#Defaults to true
DisablePickupItemsOnKitPvP: true
  
Death:
#Custom death message
  Tell: 'You have died to &7%player%&a! You lost 50 coins.'
  
#Custom kill message  
Kill:
  Tell: 'You killed &7%player%&a, you earned 100 coins.'


 # Enable sending your server address to bStats? This could get you a couple more players. =)
 # Defaults to true
SendIPAddressData: true

#Put here the cmds that are be blocked in kitpvp
#Bypass permission: kitpvp.unblockedcmds
BLOCKED_COMMANDS:
- /warp
- /spawn
- /ewarp
- /espawn
- /server
- /sw
- /skywars
- /bw
- /bedwars
- /mines
status:
  retaliado1:
    kills: 2
    mortes: 0
  retaliado2:
    kills: 2
    mortes: 0
Spawn:
  World: world
  X: 45.80294662701026
  Y: 124.86933315841993
  Z: -91.71575866737658
  Pitch: 42.90001
  Yaw: -9.5999975
SpawnD:
  World: world
  X: 45.80294662701026
  Y: 124.86933315841993
  Z: -91.71575866737658
  Pitch: 42.90001
  Yaw: -9.5999975  
 

  
